export interface SEOConfig {
  siteName: string;
  defaultTitle: string;
  titleTemplate: string;
  defaultDescription: string;
  defaultKeywords: string[];
  primaryDomainCom: string;
  primaryDomainLk: string;
  primaryDomainSriLanka: string;
  defaultOgImage: string;
  twitterHandle: string;
  location: {
    streetAddress: string;
    addressLocality: string;
    addressRegion: string;
    postalCode: string;
    addressCountry: string;
    latitude: number;
    longitude: number;
    elevation: string;
  };
  contact: {
    telephone: string;
    email: string;
  };
}

export const defaultSEOConfig: SEOConfig = {
  siteName: "Ocean Air Weligama",
  defaultTitle: "Ocean Air Weligama | Beachfront Hotel & Villa in Weligama | Best Surf Stay",
  titleTemplate: "%s | Ocean Air Weligama Hotel & Villa",
  defaultDescription:
    "Stay at Ocean Air Weligama, a beachfront hotel and villa in Weligama, Sri Lanka. Enjoy sea view rooms, surfing, comfortable accommodation, free WiFi, and the perfect beach holiday. Book direct for the best rates.",
  defaultKeywords: [
    // Exact Brand & Domain Keywords
    "ocean air weligama",
    "Ocean Air Weligama",
    "ocean air weligama sri lanka",
    "Ocean Air Weligama Sri Lanka",
    "ocean air weligama hotel",
    "Ocean Air Weligama Hotel",
    "ocean air weligama villa",
    "Ocean Air Weligama Villa",
    "ocean air weligama hotel & villa",
    "Ocean Air Weligama Hotel & Villa",
    "ocean air weligama pelana",
    "Ocean Air Weligama Pelana",
    "ocean air sri lanka",
    "Ocean Air Sri Lanka",
    "Ocean Air Guesthouse",
    "Ocean Air Villa",
    "oceanairweligama",
    "oceanair weligama",
    "ocean air welgama",
    "ocean air welligama",
    "oceanairweligama.com",
    "oceanairweligama.lk",
    "oceanairsrilanka.com",
    "Ocean Air Weligama LK",
    "Ocean Air Weligama COM",
    "Ocean",
    "Weligama",
    "Ocean Weligama",
    "Ocean Weligama Hotel",
    "Ocean Weligama Villa",

    // Weligama Hotels & Accommodation Keywords
    "Weligama hotel",
    "Beachfront hotel Weligama",
    "Weligama beach hotel",
    "Hotels in Weligama",
    "Best hotel in Weligama",
    "Weligama accommodation",
    "Weligama villa",
    "Beach villa Weligama",
    "Ocean view hotel Weligama",
    "Sea view hotel Weligama",
    "Weligama guest house",
    "Guesthouse Weligama",
    "Stay in Weligama",
    "Beach stay Weligama",
    "Luxury hotel Weligama",
    "Boutique hotel Weligama",
    "Surf hotel Weligama",
    "Hotel near Weligama Beach",
    "Weligama Sri Lanka hotel",
    "Best accommodation Weligama",
    "Book hotel Weligama",
    "Hotel booking Weligama",
    "Cheap hotel Weligama",
    "Affordable hotel Weligama",
    "Best hotel deals Weligama",
    "Beach hotel deals Weligama",
    "Weligama holiday stay",
    "Holiday villa Weligama",
    "Family hotel Weligama",
    "Romantic hotel Weligama",
    "Honeymoon hotel Weligama",
    "Vacation rental Weligama",
    "Weekend stay Weligama",
    "Best beachfront hotel in Weligama",
    "Affordable beachfront hotel Weligama",
    "Ocean view rooms in Weligama",
    "Best guesthouse in Weligama",
    "Hotel near Weligama surfing",
    "Romantic beach hotel Weligama",
    "Family villa Weligama",
    "Boutique beachfront hotel",
    "Budget accommodation near beach",
    "Hotel near Weligama Bay",
    "Stay near Weligama surf point",
    "Best stay in Weligama",
    "Weligama beachfront villa",
    "Weligama coastal stay",
    "Weligama holiday hotel",
    "Stay near Weligama Bay",
    "Oceanfront rooms Weligama",
    "Weligama beach vacation",
    "Pelena Weligama hotel",
    "Hotel in Pelena",
    "Beach hotel Pelena",
    "Weligama Bay hotel",
    "Hotel near Weligama Railway Station",

    // Beachfront & Ocean View Keywords
    "Oceanfront accommodation",
    "Hotel with beach access",
    "Sri Lanka beach accommodation",
    "Oceanfront hotel Sri Lanka",
    "Beachfront villa Sri Lanka",
    "Beach hotel Sri Lanka",
    "Indian Ocean hotel",
    "Oceanfront villa",
    "Sea facing rooms",
    "Beach holiday Sri Lanka",
    "Tropical beach hotel",
    "Beach escape Sri Lanka",
    "Coastal accommodation",
    "Beachfront guesthouse",
    "Ocean view rooms",
    "Beachfront rooms",
    "Beach holiday villa",
    "Ocean holiday",
    "Sea breeze accommodation",
    "Beach resort Weligama",
    "Beach vacation Sri Lanka",
    "Beach house Weligama",
    "Oceanfront stay",
    "Beachside hotel",
    "Beachfront rooms Sri Lanka",
    "Sunset hotel",
    "Sunrise beach hotel",
    "Relaxing beach stay",
    "Sea view accommodation Sri Lanka",
    "Beachfront guesthouse Sri Lanka",
    "Beach holiday accommodation",
    "Oceanfront guesthouse",
    "Peaceful beachfront stay",
    "Hotel with ocean views",
    "Relaxing beach accommodation",
    "Beach holiday with family",
    "Best sea view hotel",
    "Affordable oceanfront hotel",
    "Comfortable beach villa",
    "Best beach accommodation",
    "Hotel close to beach",
    "Best beachfront guesthouse",
    "Indian Ocean accommodation",
    "Holiday villa near beach",
    "Sea view guesthouse",
    "Best ocean view accommodation",
    "Beachfront holiday home",
    "Luxury beachfront villa",
    "Hotel with sea views",
    "Ocean holiday Sri Lanka",
    "Best beachfront accommodation Sri Lanka",

    // Surfing & Activity Keywords
    "Hotel near surf point",
    "Surf hotel Sri Lanka",
    "Surf accommodation Weligama",
    "Surf camp Weligama",
    "Weligama surf stay",
    "Hotel near surf beach",
    "Surfing holiday Sri Lanka",
    "Surf villa Weligama",
    "Beginner surfing Weligama",
    "Surf lessons Weligama",
    "Surf accommodation Sri Lanka",
    "Surf vacation",
    "Surf travel Sri Lanka",
    "Weligama surfing",
    "Best surf hotel",
    "Hotel for surfers",
    "Surf beach hotel",
    "Surf holiday Weligama",
    "Surf accommodation near beach",
    "Surf trip Sri Lanka",
    "Stay near surf point",
    "Best hotel for surfers",
    "Surf and stay Weligama",
    "Sri Lanka surfing holiday",
    "Sri Lanka surf accommodation",
    "Hotel near whale watching",
    "Weligama Surf Resort",
    "Surfing Weligama Sri Lanka",
    "Weligama Surf School",
    "Weligama Yoga Retreat",
    "Scooter Rental Weligama",
    "Weligama Airport Transfer",

    // Regional, Location & Nearby Attraction Keywords
    "Visit Weligama",
    "Explore Weligama",
    "Southern Sri Lanka hotels",
    "South Coast Sri Lanka",
    "Hotels near Mirissa",
    "Hotel near Galle",
    "Sri Lanka travel",
    "Sri Lanka holidays",
    "Travel Sri Lanka",
    "Best places in Weligama",
    "Weligama tourism",
    "Sri Lanka vacation",
    "Holiday in Sri Lanka",
    "Tropical vacation",
    "Coastal holiday",
    "Island getaway",
    "Sri Lanka beach holiday",
    "Holiday accommodation",
    "Beach destination",
    "Tourist accommodation",
    "Hotels near Mirissa Beach",
    "Holiday villa in Sri Lanka",
    "Hotels on Sri Lanka South Coast",
    "Tropical villa Sri Lanka",
    "Beach villa for couples",
    "Hotel for digital nomads",
    "Remote work hotel Sri Lanka",
    "Hotel near coconut tree hill",
    "Stay close to Mirissa",
    "Hotel near Galle Fort",
    "Hotels near Matara",
    "Hotel near Turtle Bay",
    "Southern Province hotel",
    "Sri Lanka south coast hotel",
    "Affordable villa Sri Lanka",

    // Hotel Room Amenities, Comfort & Guest Types Keywords
    "Weligama room booking",
    "Direct booking hotel Weligama",
    "Free WiFi hotel",
    "Air conditioned rooms",
    "Hot water rooms",
    "Private bathroom hotel",
    "Comfortable hotel",
    "Family friendly hotel",
    "Couples accommodation",
    "Budget beachfront hotel",
    "Premium rooms",
    "Deluxe rooms",
    "Superior sea view room",
    "Standard double room",
    "Ocean facing balcony",
    "Quiet accommodation",
    "Relaxing holiday",
    "Peaceful stay",
    "Nature escape",
    "Clean hotel Weligama",
    "Comfortable accommodation",
    "Best value hotel",
    "Friendly staff hotel",
    "Sri Lankan hospitality",
    "Modern rooms",
    "Scenic hotel",
    "Cozy guesthouse",
    "Vacation hotel",

    // Misspellings & Multilingual Keywords
    "welgama hotel",
    "welgama hotels",
    "welgama villa",
    "welgama resorts",
    "welligama hotel",
    "welligama resorts",
    "welligama beach hotel",
    "welgama surf",
    "welgama sri lanka hotel",
    "Best place to stay in Weligama",
    "Sri Lanka South Coast Luxury Hotel",
    "Barefoot Luxury Sri Lanka",
    "Beachside Boutique Villa Weligama",
    "Weligama Bay Accommodation",
    "Direct Booking Weligama Hotel",
    "Hotel Weligama Sri Lanka",
    "Weligama Unterkünfte",
    "Отель Велигама Шри Ланка",
    "Hôtel Weligama Sri Lanka",
  ],
  primaryDomainCom: "https://oceanairweligama.com",
  primaryDomainLk: "https://oceanairweligama.lk",
  primaryDomainSriLanka: "https://oceanairsrilanka.com",
  defaultOgImage: "https://oceanairweligama.com/logo.jpg",
  twitterHandle: "@oceanairweligama",
  location: {
    streetAddress: "No 42 Jayasayurupura Pelana",
    addressLocality: "Weligama",
    addressRegion: "Southern Province",
    postalCode: "81700",
    addressCountry: "LK",
    latitude: 5.9723,
    longitude: 80.4286,
    elevation: "3m",
  },
  contact: {
    telephone: "+94765791763",
    email: "pelanawhitehouse@gmail.com",
  },
};

/**
 * Resolves canonical URL ensuring .com, .lk, and oceanairsrilanka.com domains unify link authority cleanly.
 */
export function getCanonicalUrl(path: string = ""): string {
  const cleanPath = path.startsWith("/") ? path : `/${path}`;
  if (typeof window !== "undefined") {
    const host = window.location.hostname;
    if (host.includes("oceanairsrilanka.com")) {
      return `${defaultSEOConfig.primaryDomainSriLanka}${cleanPath}`;
    }
    if (host.endsWith(".lk")) {
      return `${defaultSEOConfig.primaryDomainLk}${cleanPath}`;
    }
  }
  return `${defaultSEOConfig.primaryDomainCom}${cleanPath}`;
}
